### ISSUE TITLE
Global nav missing from careers page on www.canonical.com

### ISSUE THREAD

**Issue by frankiegranato** [canonical-websites/www.canonical.com#211]
The global nav is missing from the taleo 'search' page. Possibly caused by no-cookie-message? 
https://ldd.tbe.taleo.net/ldd03/ats/careers/jobSearch.jsp

**Comment by pmahnke** [comment]
@frankiegranato these pages are not on canonical.com, but hosted by our partner, taleo.  It would be impossible to put on their site.  Additionally we are soon moving providers; however, it will be impossible to add cookies and nav there as well.  However, we are going to be making it look less like the www.canonical.com site so that people are more aware they have moved off the site.

**Comment by anthonydillon** [comment]
I agree, if it's being replaced there is no need to add them but it is
possible. Both packages push there build files to the asset manager when
released.

Therefore, we just need to include the built files in the header of the
template and it should work.
