### ISSUE TITLE
canonical.com resources feed failing to load

### ISSUE THREAD

**Issue by chuckbutler** [canonical-websites/www.canonical.com#244]
![selection_181](https://user-images.githubusercontent.com/246944/37305408-5292aac2-2602-11e8-883e-9c5763bf4925.png)

And i just noticed the news feed is failing as well.

**Comment by anthonydillon** [comment]
Thank you very much for reporting this issue. We will try and get a fix in place as soon as possible.

**Comment by steverydz** [comment]
@nottrobin I think this may be related to https://github.com/canonical-websites/developer.ubuntu.com/issues/350

**Comment by nottrobin** [comment]
@steverydz not quite. In this case we can solve it by using the feed from admin.insights.ubuntu.com (whose cert word) rather than insights.ubuntu.com (which has the certificate problem mentioned in https://github.com/canonical-websites/developer.ubuntu.com/issues/350), similar to what was done in https://github.com/canonical-websites/www.ubuntu.com/pull/2789 and improved in https://github.com/canonical-websites/www.ubuntu.com/pull/2832.

Would you be able to have a go at copying that solution for www.canonical.com?

**Comment by steverydz** [comment]
@nottrobin OK thanks. I'll take a look.
